---
abstract: 'Terminal widget for showing status, CPU and memory'
author:
  - 'Tom Molesworth <TEAM@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::CheckDeps: '0.010'
  Test::Fatal: '0.010'
  Test::More: '0.98'
  Test::Refcount: '0.07'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.031, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Tickit-Widget-Statusbar
no_index:
  directory:
    - eg
    - share
    - shares
    - t
    - xt
provides:
  Tickit::Widget::Statusbar:
    file: lib/Tickit/Widget/Statusbar.pm
    version: '0.006'
  Tickit::Widget::Statusbar::CPU:
    file: lib/Tickit/Widget/Statusbar/CPU.pm
    version: '0.006'
  Tickit::Widget::Statusbar::Clock:
    file: lib/Tickit/Widget/Statusbar/Clock.pm
    version: '0.006'
  Tickit::Widget::Statusbar::Icon:
    file: lib/Tickit/Widget/Statusbar/Icon.pm
    version: '0.006'
  Tickit::Widget::Statusbar::Memory:
    file: lib/Tickit/Widget/Statusbar/Memory.pm
    version: '0.006'
  Tickit::Widget::Statusbar::WidgetList:
    file: lib/Tickit/Widget/Statusbar/WidgetList.pm
    version: '0.006'
requires:
  BSD::Resource: '0'
  Format::Human::Bytes: '0'
  Memory::Usage: '0'
  String::Tagged: '0.09'
  Tickit: '0.71'
  Tickit::Widget: '0.54'
  Tickit::Widget::Progressbar: '0.100'
  Time::HiRes: '0'
  curry: '0'
  parent: '0'
resources:
  bugtracker: https://github.com/team-at-cpan/Tickit-Widget-Statusbar/issues
  homepage: https://github.com/team-at-cpan/Tickit-Widget-Statusbar
  repository: https://github.com/team-at-cpan/Tickit-Widget-Statusbar.git
version: '0.006'
x_authority: cpan:TEAM
x_contributors:
  - 'Tom Molesworth <tom@perlsite.co.uk>'
x_generated_by_perl: v5.38.0
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
